trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  # Define workspace folders
  inbound_data: '$(Pipeline.Workspace)\Inbound_Data'
  outbound_data: '$(Pipeline.Workspace)\Outbound_Data'
  plots_data: '$(Pipeline.Workspace)\Plots'
  models_data: '$(Pipeline.Workspace)\Models_Created'

stages:
- stage: Build
  displayName: 'Build and Run ML Pipeline'
  jobs:
  - job: MLJob
    displayName: 'Run ML Model & Generate Outputs'
    steps:

    # Checkout repo
    - checkout: self

    # Install dependencies
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Python Dependencies'

    # Ensure folders exist
    - script: |
        mkdir "$(inbound_data)" || echo "Folder exists"
        mkdir "$(outbound_data)" || echo "Folder exists"
        mkdir "$(plots_data)" || echo "Folder exists"
        mkdir "$(models_data)" || echo "Folder exists"
      displayName: 'Create Workspace Folders'

    # Run Python script
    - script: |
        python src/SOK_XGBoost_Gradnt_Boost_Breast_Cancer.py
      displayName: 'Run Breast Cancer ML Script'

    # Publish pipeline artifacts
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(outbound_data)'
        artifact: 'Patient_Predictions'
      displayName: 'Publish Patient Predictions'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(plots_data)'
        artifact: 'Plots'
      displayName: 'Publish Plots'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(models_data)'
        artifact: 'Trained_Model'
      displayName: 'Publish ML Model'
