trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  inbound_data: 'E:\AI_Training\CPT_Data\Inbound_Data'
  outbound_data: 'E:\AI_Training\CPT_Data\Outbound_Data'
  plots_data: 'E:\AI_Training\CPT_Data\Plots'
  models_data: 'E:\AI_Training\CPT_Data\Models_Created'

jobs:
- job: ML_Prediction
  displayName: 'Run Breast Cancer Prediction ML Job'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  - script: |
      python src/SOK_XGBoost_Gradnt_Boost_Breast_Cancer.py ^
        --input-csv "$(inbound_data)\Breast_Cancer_Prediction_Data.csv" ^
        --output-csv "$(outbound_data)\All_Patient_Predictions_OUT.csv" ^
        --output-plots "$(plots_data)" ^
        --output-model "$(models_data)\Breast_Cancer_Prediction_Model.json"
    displayName: 'Run Breast Cancer ML Script with Arguments'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(outbound_data)'
      artifact: 'Patient_Predictions'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(plots_data)'
      artifact: 'Prediction_Plots'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(models_data)'
      artifact: 'ML_Models'
      publishLocation: 'pipeline'
