import os

# Create relative outputs folder
output_dir = os.path.join(os.getcwd(), "outputs")
os.makedirs(output_dir, exist_ok=True)

# Example saving predictions
pred_file = os.path.join(output_dir, "Patient_Predictions.csv")
df.to_csv(pred_file, index=False)

# Example saving plots
plot_file = os.path.join(output_dir, "prediction_plot.png")
plt.savefig(plot_file)
