# Azure Pipelines YAML
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  pythonVersion: '3.10'

steps:
# Checkout repo
- checkout: self   # Fixed checkout syntax

# Setup Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install pandas matplotlib seaborn scikit-learn xgboost
  displayName: 'Install Python packages'

# Run ML script
- script: |
    python src/breast_cancer_ml.py
  displayName: 'Run Breast Cancer ML Script'

# Publish outputs
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'out_files'
    artifact: 'BreastCancerML_Outputs'
    publishLocation: 'pipeline'
  displayName: 'Publish ML Outputs'
