trigger:
  branches:
    include:
      - main

variables:
  inbound_csv: '$(Build.SourcesDirectory)\CPT_Data\Inbound_Data\Breast_Cancer_Prediction_Data.csv'
  outbound_dir: '$(Build.ArtifactStagingDirectory)\Outbound_Data'
  plots_dir: '$(Build.ArtifactStagingDirectory)\Plots'
  model_file: '$(Build.ArtifactStagingDirectory)\Models_Created\Breast_Cancer_Prediction_Model.json'

jobs:
- job: BuildAndRun
  displayName: 'Build and Run ML Pipeline'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: python src/SOK_XGBoost_Gradnt_Boost_Breast_Cancer.py --input-csv $(inbound_csv) --output-csv $(outbound_dir) --output-plots $(plots_dir) --output-model $(model_file)
    displayName: 'Run Breast Cancer ML Script'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(outbound_dir)'
      artifact: 'Patient_Predictions'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(plots_dir)'
      artifact: 'Prediction_Plots'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)\Models_Created'
      artifact: 'ML_Model'
      publishLocation: 'pipeline'
