trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  pythonVersion: '3.10'

steps:
- task: Checkout@1
  displayName: 'Checkout Repository'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python packages'

- script: |
    python src/breast_cancer_ml.py
  displayName: 'Run Breast Cancer ML Script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'E:/AI_Training/CPT_AZURE/ML/out_files'
    artifact: 'BreastCancerML_Outputs'
    publishLocation: 'pipeline'
  displayName: 'Publish ML Outputs'
