# azure-pipelines.yml
trigger:
  - main  # Automatically run on push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1️⃣ Use Python 3.10
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true
  displayName: 'Use Python 3.10'

# 2️⃣ Upgrade pip and install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install --prefer-binary -r requirements.txt
  displayName: 'Install Python dependencies'

# 3️⃣ Run ML script
- script: |
    python src/SOK_XGBoost_Gradnt_Boost_Breast_Cancer.py
  displayName: 'Run Breast Cancer Prediction Script'

# Optional: publish outputs (if you want artifacts to download from pipeline)
# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: 'src/output'   # Replace with your actual output folder
#     artifact: 'MLOutputs'
#     publishLocation: 'pipeline'
